# vim: ft=dockerfile
FROM tda283/tester

USER root
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash
RUN apt-get update && apt-get install -y nodejs

# Install WABT
RUN curl -OL "https://github.com/WebAssembly/wabt/releases/download/1.0.29/wabt-1.0.29-ubuntu.tar.gz"
RUN tar -xzf "wabt-1.0.29-ubuntu.tar.gz" -C "/home/user"
RUN rm "wabt-1.0.29-ubuntu.tar.gz"
RUN mv "/home/user/wabt-1.0.29" "/home/user/.wabt"
ENV PATH="/home/user/.wabt/bin:$PATH"

USER user
WORKDIR /home/user/tda283/tester
CMD /bin/bash
